apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  selector:
    matchLabels:
      app: react-app
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: satyamk134/laundary-react-app
        ports:
        - containerPort: 80


