apiVersion: v1
kind: Service
metadata:
  name: my-react-app
  labels:
    name: my-react-app
spec:
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: 80
  selector:
    app: react-app