apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: satyamk134/laundary-node-app
        ports:
        - containerPort: 4343

